[all_nodes]
redis-node-1 ansible_host=10.10.0.11
redis-node-2 ansible_host=10.10.0.12
redis-node-3 ansible_host=10.10.0.13
redis-node-4 ansible_host=10.10.0.14
redis-node-5 ansible_host=10.10.0.15
redis-node-6 ansible_host=10.10.0.16

[masters]
redis-node-1 redis_role=master
redis-node-2 redis_role=master
redis-node-3 redis_role=master

[replicas]
redis-node-4 redis_role=replica master_host=10.10.0.11
redis-node-5 redis_role=replica master_host=10.10.0.12
redis-node-6 redis_role=replica master_host=10.10.0.13

[all_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=/home/Ansible/id_rsa
